package noppes.npcs.constants;


public enum EnumPacketClient {

   CHAT("CHAT", 0),
   MESSAGE("MESSAGE", 1),
   SYNCRECIPES_ADD("SYNCRECIPES_ADD", 2),
   SYNCRECIPES_WORKBENCH("SYNCRECIPES_WORKBENCH", 3),
   DIALOG("DIALOG", 4),
   QUEST_COMPLETION("QUEST_COMPLETION", 5),
   EDIT_NPC("EDIT_NPC", 6),
   PLAY_SOUND("PLAY_SOUND", 7),
   PLAY_MUSIC("PLAY_MUSIC", 8),
   UPDATE_NPC("UPDATE_NPC", 9),
   ROLE("ROLE", 10),
   GUI("GUI", 11),
   PARTICLE("PARTICLE", 12),
   DELETE_NPC("DELETE_NPC", 13),
   SCROLL_LIST("SCROLL_LIST", 14),
   SCROLL_DATA("SCROLL_DATA", 15),
   SCROLL_DATA_PART("SCROLL_DATA_PART", 16),
   SCROLL_SELECTED("SCROLL_SELECTED", 17),
   GUI_REDSTONE("GUI_REDSTONE", 18),
   GUI_WAYPOINT("GUI_WAYPOINT", 19),
   GUI_DATA("GUI_DATA", 20),
   GUI_ERROR("GUI_ERROR", 21),
   GUI_CLOSE("GUI_CLOSE", 22),
   VILLAGER_LIST("VILLAGER_LIST", 23),
   CHATBUBBLE("CHATBUBBLE", 24),
   SYNCRECIPES_CARPENTRYBENCH("SYNCRECIPES_CARPENTRYBENCH", 25),
   CLONE("CLONE", 26),
   OPEN_BOOK("OPEN_BOOK", 27);
   // $FF: synthetic field
   private static final EnumPacketClient[] $VALUES = new EnumPacketClient[]{CHAT, MESSAGE, SYNCRECIPES_ADD, SYNCRECIPES_WORKBENCH, DIALOG, QUEST_COMPLETION, EDIT_NPC, PLAY_SOUND, PLAY_MUSIC, UPDATE_NPC, ROLE, GUI, PARTICLE, DELETE_NPC, SCROLL_LIST, SCROLL_DATA, SCROLL_DATA_PART, SCROLL_SELECTED, GUI_REDSTONE, GUI_WAYPOINT, GUI_DATA, GUI_ERROR, GUI_CLOSE, VILLAGER_LIST, CHATBUBBLE, SYNCRECIPES_CARPENTRYBENCH, CLONE, OPEN_BOOK};


   private EnumPacketClient(String var1, int var2) {}

}
